---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"

  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    commit-message:
      prefix: "nuget"
    groups:
      Avalonia:
        patterns:
          - "*Avalonia*"
      Silk.NET:
        patterns:
          - "Silk.NET*"
      OpenTK:
        patterns:
          - "OpenTK*"
      SixLabors:
        patterns:
          - "SixLabors*"
      NUnit:
        patterns:
          - "NUnit*"
      Unicorn:
        patterns:
          - "*Unicorn*"
